name: Members Push Alarm
on:
  push:
    paths:
      - 'members/**'

jobs:
  members-push-alarm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./slack/requirements.txt ]; then pip install -r ./slack/requirements.txt; fi
    - name: Check Diff files
      run: git diff --name-only HEAD^ HEAD > diff.txt
    - name: Run python script
      run: python ./slack/members-push-alarm.py
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
